### ISSUE TITLE
Solr Cloud ZK status error

### ISSUE THREAD

**Issue by krishnachalla-hv** [bloomberg/solr-operator#129]
**Describe the bug**
When I click on the ZK status in solr Admin UI exception is thrown.

**To Reproduce**
1. Go to 'Solr Admin UI'
2. Click on 'Cloud -> ZK status'

`2020-08-11 12:13:15.176 INFO  (qtp176683244-14) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/zookeeper/status params={wt=json&_=1597147993233} status=500 QTime=22
2020-08-11 12:13:15.181 ERROR (qtp176683244-14) [   ] o.a.s.s.HttpSolrCall null:java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.apache.solr.handler.admin.ZookeeperStatusHandler.monitorZookeeper(ZookeeperStatusHandler.java:188)
	at org.apache.solr.handler.admin.ZookeeperStatusHandler.getZkStatus(ZookeeperStatusHandler.java:98)
	at org.apache.solr.handler.admin.ZookeeperStatusHandler.handleRequestBody(ZookeeperStatusHandler.java:79)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:199)
	at org.apache.solr.servlet.HttpSolrCall.handleAdmin(HttpSolrCall.java:734)
	at org.apache.solr.servlet.HttpSolrCall.handleAdminRequest(HttpSolrCall.java:715)
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:496)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:377)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:323)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Expected behavior**
It should display the ZK connection string etc.

**Screenshots**
![ZK status error](https://user-images.githubusercontent.com/60733731/89896315-e34cf580-dbfa-11ea-9a08-406faf33a53c.png)

**Comment by HoustonPutman** [comment]
Thanks for reporting this @krishnachalla-hv, especially with the stack trace.

What version of Solr are you running? I've seen this issue pop up on solr that aren't running in Kube before, but the Solr version will definitely help nail down the reason.

**Comment by krishnachalla-hv** [comment]
I am using 7.5.0-slim docker image.

**Comment by racoon63** [comment]
Got the same error with version 8.1.1. Updated to version 8.4.1 and now it works for me with known admin webUI error but correct ZK connection string.

**Comment by krishnachalla-hv** [comment]
I have installed 8.4.1-slim image just to see whether it works or not except the ZK status everything else is displayed properly.
![Solr-8 4 1-error](https://user-images.githubusercontent.com/60733731/91018839-bc84bb00-e60d-11ea-8d3b-7cea6e3b3055.png)

**Comment by HoustonPutman** [comment]
Yeah, so by using the single zookeeper host for the client string, it shows this error. I tested listing all of the zookeeper hosts out and the error goes away. I'll create a PR to get that fixed.

**Comment by krishnachalla-hv** [comment]
@HoustonPutman If I user solr image below version **8** I am getting the `index length issue`

**Comment by HoustonPutman** [comment]
Below version 8.3/8.4 you are going to get that error because Solr didn't know how to correctly parse the Zookeeper `conf` response.

You can read about it here: https://issues.apache.org/jira/browse/SOLR-13672
