### ISSUE TITLE
Null Pointer when running Exporter

### ISSUE THREAD

**Issue by ericlarssen-wf** [bloomberg/solr-operator#154]
**Describe the bug**
After deploying the solr cloud example to my cluster (not minikube), I decided to add the the prometheus exporter as well, however was hit with a wall of stack traces in the exporter pod.

``` log
WARN  - 2020-10-29 17:55:44.592; org.apache.solr.prometheus.scraper.Async; Error occurred during metrics collection => java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:?]
	at org.apache.solr.prometheus.scraper.Async.lambda$null$1(Async.java:45) ~[solr-prometheus-exporter-8.2.0.jar:8.2.0 31d7ec7bbfdcd2c4cc61d9d35e962165410b65fe - ivera - 2019-07-19 15:10:57]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
	at org.apache.solr.prometheus.scraper.Async.lambda$waitForAllSuccessfulResponses$3(Async.java:43) ~[solr-prometheus-exporter-8.2.0.jar:8.2.0 31d7ec7bbfdcd2c4cc61d9d35e962165410b65fe - ivera - 2019-07-19 15:10:57]
	at java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:209) ~[solr-solrj-8.2.0.jar:8.2.0 31d7ec7bbfdcd2c4cc61d9d35e962165410b65fe - ivera - 2019-07-19 15:11:07]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at org.apache.solr.prometheus.collector.SchedulerMetricsCollector.lambda$collectMetrics$0(SchedulerMetricsCollector.java:92) ~[solr-prometheus-exporter-8.2.0.jar:8.2.0 31d7ec7bbfdcd2c4cc61d9d35e962165410b65fe - ivera - 2019-07-19 15:10:57]
	... 5 more
Caused by: java.lang.NullPointerException
	at org.apache.solr.prometheus.scraper.SolrScraper.request(SolrScraper.java:112) ~[solr-prometheus-exporter-8.2.0.jar:8.2.0 31d7ec7bbfdcd2c4cc61d9d35e962165410b65fe - ivera - 2019-07-19 15:10:57]
	at org.apache.solr.prometheus.scraper.SolrCloudScraper.collections(SolrCloudScraper.java:133) ~[solr-prometheus-exporter-8.2.0.jar:8.2.0 31d7ec7bbfdcd2c4cc61d9d35e962165410b65fe - ivera - 2019-07-19 15:10:57]
	at org.apache.solr.prometheus.collector.CollectionsCollector.collect(CollectionsCollector.java:35) ~[solr-prometheus-exporter-8.2.0.jar:8.2.0 31d7ec7bbfdcd2c4cc61d9d35e962165410b65fe - ivera - 2019-07-19 15:10:57]
	at org.apache.solr.prometheus.collector.SchedulerMetricsCollector.lambda$collectMetrics$0(SchedulerMetricsCollector.java:90) ~[solr-prometheus-exporter-8.2.0.jar:8.2.0 31d7ec7bbfdcd2c4cc61d9d35e962165410b65fe - ivera - 2019-07-19 15:10:57]
	... 5 more
INFO  - 2020-10-29 17:55:44.593; org.apache.solr.prometheus.collector.SchedulerMetricsCollector; Completed metrics collection
```

**To Reproduce**
1. Install zk and solr operators
2. Install solrcloud example and prometheus exporter example
3. `kubectl logs pod/solrprometheusexporter-sample-solr-metrics-....`

**Expected behavior**
No stack trace

**Screenshots**

**Environment (please complete the following information):**
 - EKS
 - Helm
 - Tag = 8.2.0

**Additional context**
I want to forward my metrics to new relic, but need to use the exporter so that newrelic prometheus can scrape the endpoint

**Comment by ericlarssen-wf** [comment]
After a fresh reinstall the issue has subsided. closing.
