### ISSUE TITLE
Solr registers with incorrect port 80 in Zookeeper

### ISSUE THREAD

**Issue by gmaiztegi** [bloomberg/solr-operator#84]
**Describe the bug**

Solr registers itself in Zookeeper using 80 as port instead of 8983, making it fail when trying to contact itself.

These are the logs at the beginning:

```
Starting Solr
2020-02-26 09:10:35.481 INFO  (main) [   ] o.e.j.u.log Logging initialized @988ms to org.eclipse.jetty.util.log.Slf4jLog
2020-02-26 09:10:35.695 WARN  (main) [   ] o.e.j.s.AbstractConnector Ignoring deprecated socket close linger time
2020-02-26 09:10:35.695 WARN  (main) [   ] o.e.j.x.XmlConfiguration Deprecated method public void org.eclipse.jetty.server.ServerConnector.setSoLingerTime(int) in file:///opt/solr-8.4.1/server/etc/jetty-http.xml
2020-02-26 09:10:35.706 INFO  (main) [   ] o.e.j.s.Server jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 11.0.6+10
2020-02-26 09:10:35.730 INFO  (main) [   ] o.e.j.d.p.ScanningAppProvider Deployment monitor [file:///opt/solr-8.4.1/server/contexts/] at interval 0
2020-02-26 09:10:35.966 INFO  (main) [   ] o.e.j.w.StandardDescriptorProcessor NO JSP Support for /solr, did not find org.apache.jasper.servlet.JspServlet
2020-02-26 09:10:35.985 INFO  (main) [   ] o.e.j.s.session DefaultSessionIdManager workerName=node0
2020-02-26 09:10:35.987 INFO  (main) [   ] o.e.j.s.session No SessionScavenger set, using defaults
2020-02-26 09:10:35.992 INFO  (main) [   ] o.e.j.s.session node0 Scavenging every 660000ms
2020-02-26 09:10:36.091 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter Using logger factory org.apache.logging.slf4j.Log4jLoggerFactory
2020-02-26 09:10:36.098 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter  ___      _       Welcome to Apache Solr™ version 8.4.1
2020-02-26 09:10:36.106 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter / __| ___| |_ _   Starting in cloud mode on port 8983
2020-02-26 09:10:36.106 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter \__ \/ _ \ | '_|  Install dir: /opt/solr
2020-02-26 09:10:36.107 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter |___/\___/_|_|    Start time: 2020-02-26T09:10:36.107075Z
2020-02-26 09:10:36.107 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter Log level override, property solr.log.level=INFO
2020-02-26 09:10:36.148 INFO  (main) [   ] o.a.s.c.SolrResourceLoader Using system property solr.solr.home: /var/solr/data
2020-02-26 09:10:36.200 INFO  (main) [   ] o.a.s.c.c.ConnectionManager Waiting for client to connect to ZooKeeper
2020-02-26 09:10:51.027 INFO  (zkConnectionManagerCallback-2-thread-1) [   ] o.a.s.c.c.ConnectionManager zkClient has connected
2020-02-26 09:10:51.027 INFO  (main) [   ] o.a.s.c.c.ConnectionManager Client is connected to ZooKeeper
2020-02-26 09:10:51.144 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter Loading solr.xml from SolrHome (not found in ZooKeeper)
2020-02-26 09:10:51.148 INFO  (main) [   ] o.a.s.c.SolrXmlConfig Loading container configuration from /var/solr/data/solr.xml
2020-02-26 09:10:51.211 INFO  (main) [   ] o.a.s.c.SolrXmlConfig MBean server found: com.sun.jmx.mbeanserver.JmxMBeanServer@732d0d24, but no JMX reporters were configured - adding default JMX reporter.
2020-02-26 09:10:51.921 INFO  (main) [   ] o.a.s.h.c.HttpShardHandlerFactory Host whitelist initialized: WhitelistHostChecker [whitelistHosts=null, whitelistHostCheckingEnabled=true]
2020-02-26 09:10:52.170 WARN  (main) [   ] o.e.j.u.s.S.config Trusting all certificates configured for Client@1dd7796b[provider=null,keyStore=null,trustStore=null]
2020-02-26 09:10:52.170 WARN  (main) [   ] o.e.j.u.s.S.config No Client EndPointIdentificationAlgorithm configured for Client@1dd7796b[provider=null,keyStore=null,trustStore=null]
2020-02-26 09:10:52.353 WARN  (main) [   ] o.e.j.u.s.S.config Trusting all certificates configured for Client@1a2bcd56[provider=null,keyStore=null,trustStore=null]
2020-02-26 09:10:52.353 WARN  (main) [   ] o.e.j.u.s.S.config No Client EndPointIdentificationAlgorithm configured for Client@1a2bcd56[provider=null,keyStore=null,trustStore=null]
2020-02-26 09:10:52.364 INFO  (main) [   ] o.a.s.c.ZkContainer Zookeeper client=matching-solrcloud-zookeeper-client:2181/
2020-02-26 09:10:52.383 INFO  (main) [   ] o.a.s.c.c.ConnectionManager Waiting for client to connect to ZooKeeper
2020-02-26 09:10:52.391 INFO  (zkConnectionManagerCallback-9-thread-1) [   ] o.a.s.c.c.ConnectionManager zkClient has connected
2020-02-26 09:10:52.391 INFO  (main) [   ] o.a.s.c.c.ConnectionManager Client is connected to ZooKeeper
2020-02-26 09:10:52.512 INFO  (main) [   ] o.a.s.c.c.ConnectionManager Waiting for client to connect to ZooKeeper
2020-02-26 09:10:52.519 INFO  (zkConnectionManagerCallback-11-thread-1) [   ] o.a.s.c.c.ConnectionManager zkClient has connected
2020-02-26 09:10:52.520 INFO  (main) [   ] o.a.s.c.c.ConnectionManager Client is connected to ZooKeeper
2020-02-26 09:10:52.656 INFO  (main) [   ] o.a.s.c.OverseerElectionContext I am going to be the leader matching-solrcloud-0.matching-solrcloud-headless:80_solr
2020-02-26 09:10:52.663 INFO  (main) [   ] o.a.s.c.Overseer Overseer (id=72301757338091522-matching-solrcloud-0.matching-solrcloud-headless:80_solr-n_0000000005) starting
2020-02-26 09:10:52.822 INFO  (OverseerStateUpdate-72301757338091522-matching-solrcloud-0.matching-solrcloud-headless:80_solr-n_0000000005) [   ] o.a.s.c.Overseer Starting to work on the main queue : matching-solrcloud-0.matching-solrcloud-headless:80_solr
2020-02-26 09:10:52.828 INFO  (main) [   ] o.a.s.c.ZkController Register node as live in ZooKeeper:/live_nodes/matching-solrcloud-0.matching-solrcloud-headless:80_solr
2020-02-26 09:10:52.878 INFO  (OverseerStateUpdate-72301757338091522-matching-solrcloud-0.matching-solrcloud-headless:80_solr-n_0000000005) [   ] o.a.s.c.c.ZkStateReader Updated live nodes from ZooKeeper... (0) -> (1)
2020-02-26 09:10:52.954 INFO  (main) [   ] o.a.s.p.PackageLoader /packages.json updated to version -1
2020-02-26 09:10:52.983 WARN  (main) [   ] o.a.s.c.CoreContainer Not all security plugins configured!  authentication=disabled authorization=disabled.  Solr is only as secure as you make it. Consider configuring authentication/authorization before exposing Solr to users internal or external.  See https://s.apache.org/solrsecurity for more info
2020-02-26 09:10:53.190 INFO  (main) [   ] o.a.s.h.a.MetricsHistoryHandler No .system collection, keeping metrics history in memory.
2020-02-26 09:10:53.304 INFO  (main) [   ] o.a.s.m.r.SolrJmxReporter JMX monitoring for 'solr.node' (registry 'solr.node') enabled at server: com.sun.jmx.mbeanserver.JmxMBeanServer@732d0d24
2020-02-26 09:10:53.305 INFO  (main) [   ] o.a.s.m.r.SolrJmxReporter JMX monitoring for 'solr.jvm' (registry 'solr.jvm') enabled at server: com.sun.jmx.mbeanserver.JmxMBeanServer@732d0d24
2020-02-26 09:10:53.311 INFO  (main) [   ] o.a.s.m.r.SolrJmxReporter JMX monitoring for 'solr.jetty' (registry 'solr.jetty') enabled at server: com.sun.jmx.mbeanserver.JmxMBeanServer@732d0d24
2020-02-26 09:10:53.352 INFO  (main) [   ] o.a.s.c.CorePropertiesLocator Found 0 core definitions underneath /var/solr/data
2020-02-26 09:10:53.465 INFO  (main) [   ] o.e.j.s.h.ContextHandler Started o.e.j.w.WebAppContext@16423501{/solr,file:///opt/solr-8.4.1/server/solr-webapp/webapp/,AVAILABLE}{/opt/solr-8.4.1/server/solr-webapp/webapp}
2020-02-26 09:10:53.477 INFO  (main) [   ] o.e.j.s.AbstractConnector Started ServerConnector@388ba540{HTTP/1.1,[http/1.1, h2c]}{0.0.0.0:8983}
2020-02-26 09:10:53.477 INFO  (main) [   ] o.e.j.s.Server Started @18987ms
2020-02-26 09:10:57.641 INFO  (qtp1635378213-18) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={} status=0 QTime=52
2020-02-26 09:10:59.562 INFO  (qtp1635378213-14) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={} status=0 QTime=7
2020-02-26 09:11:02.521 INFO  (qtp1635378213-21) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={} status=0 QTime=9
2020-02-26 09:11:07.520 INFO  (qtp1635378213-18) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={} status=0 QTime=8
2020-02-26 09:11:09.562 INFO  (qtp1635378213-19) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={} status=0 QTime=8
2020-02-26 09:11:12.521 INFO  (qtp1635378213-23) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={} status=0 QTime=8
2020-02-26 09:11:17.523 INFO  (qtp1635378213-21) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={} status=0 QTime=11
2020-02-26 09:11:19.566 INFO  (qtp1635378213-14) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={} status=0 QTime=12
2020-02-26 09:11:22.519 INFO  (qtp1635378213-16) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={} status=0 QTime=7
2020-02-26 09:11:27.518 INFO  (qtp1635378213-22) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={} status=0 QTime=6
2020-02-26 09:11:29.560 INFO  (qtp1635378213-18) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={} status=0 QTime=6
2020-02-26 09:11:32.522 INFO  (qtp1635378213-19) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={} status=0 QTime=7
2020-02-26 09:11:37.519 INFO  (qtp1635378213-17) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={} status=0 QTime=7
2020-02-26 09:11:39.560 INFO  (qtp1635378213-21) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={} status=0 QTime=6
2020-02-26 09:11:42.522 INFO  (qtp1635378213-20) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={} status=0 QTime=8
2020-02-26 09:11:47.521 INFO  (qtp1635378213-19) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={} status=0 QTime=8
2020-02-26 09:11:49.560 INFO  (qtp1635378213-17) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={} status=0 QTime=7
2020-02-26 09:11:52.523 INFO  (qtp1635378213-21) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={} status=0 QTime=11
2020-02-26 09:11:53.254 INFO  (MetricsHistoryHandler-12-thread-1) [   ] o.a.s.c.s.i.SolrClientNodeStateProvider Error on getting remote info, trying again: Server refused connection at: http://matching-solrcloud-0.matching-solrcloud-headless:80/solr
2020-02-26 09:11:53.756 INFO  (MetricsHistoryHandler-12-thread-1) [   ] o.a.s.c.s.i.SolrClientNodeStateProvider Error on getting remote info, trying again: Server refused connection at: http://matching-solrcloud-0.matching-solrcloud-headless:80/solr
2020-02-26 09:11:54.257 INFO  (MetricsHistoryHandler-12-thread-1) [   ] o.a.s.c.s.i.SolrClientNodeStateProvider Error on getting remote info, trying again: Server refused connection at: http://matching-solrcloud-0.matching-solrcloud-headless:80/solr
2020-02-26 09:11:54.758 WARN  (MetricsHistoryHandler-12-thread-1) [   ] o.a.s.c.s.i.SolrClientNodeStateProvider could not get tags from node matching-solrcloud-0.matching-solrcloud-headless:80_solr => java.lang.NullPointerException
	at org.apache.solr.client.solrj.impl.SolrClientNodeStateProvider.lambda$fetchReplicaMetrics$7(SolrClientNodeStateProvider.java:226)
java.lang.NullPointerException: null
	at org.apache.solr.client.solrj.impl.SolrClientNodeStateProvider.lambda$fetchReplicaMetrics$7(SolrClientNodeStateProvider.java:226) ~[?:?]
	at java.util.HashMap.forEach(HashMap.java:1336) ~[?:?]
	at org.apache.solr.client.solrj.impl.SolrClientNodeStateProvider.fetchReplicaMetrics(SolrClientNodeStateProvider.java:225) ~[?:?]
	at org.apache.solr.client.solrj.impl.SolrClientNodeStateProvider$AutoScalingSnitch.getRemoteInfo(SolrClientNodeStateProvider.java:271) ~[?:?]
	at org.apache.solr.common.cloud.rule.ImplicitSnitch.getTags(ImplicitSnitch.java:76) ~[?:?]
	at org.apache.solr.client.solrj.impl.SolrClientNodeStateProvider.fetchTagValues(SolrClientNodeStateProvider.java:139) ~[?:?]
	at org.apache.solr.client.solrj.impl.SolrClientNodeStateProvider.getNodeValues(SolrClientNodeStateProvider.java:128) ~[?:?]
	at org.apache.solr.handler.admin.MetricsHistoryHandler.collectGlobalMetrics(MetricsHistoryHandler.java:506) ~[?:?]
	at org.apache.solr.handler.admin.MetricsHistoryHandler.collectMetrics(MetricsHistoryHandler.java:378) ~[?:?]
	at org.apache.solr.handler.admin.MetricsHistoryHandler.lambda$new$0(MetricsHistoryHandler.java:235) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**To Reproduce**

I am creating the SolrCloud using the following yaml:

```{yaml}
apiVersion: solr.bloomberg.com/v1beta1
kind: SolrCloud
metadata:
  name: matching
  namespace: default
spec:
  replicas: 1
  solrImage:
    tag: "8"
  zookeeperRef:
    provided:
      zookeeper:
        replicas: 1
```

**Expected behavior**

I would expect the Solr instance to correctly initialize and register itself using 8983 as port.

**Environment (please complete the following information):**

We are running our cluster on AWS EKS, Kubernetes 1.14.

**Additional context**

I have also tried with versions 6 and 7 of Solr, but those had the same issue.

**Comment by whitleykeith** [comment]
I'm having the same problem, also on AWS EKS, K8 1.14. I've tried with Solr 8.4.1 and still have the same issue.

**Comment by HoustonPutman** [comment]
Thanks for reporting this!

The reason it registers itself as port 80 is that it's going through the headless service, which maps port 80 -> 8983. That way, solr listens on port 8983 but all requests to it go through port 80.

I've seen this before, as have others (#71). After a lot of digging, I think I've finally figured it out. In this issue, https://github.com/kubernetes/kubernetes/issues/20488, someone mentions that `targetPort` and `port` must be the same for headless services. I haven't seen this documented anywhere, and I have been scouring the kubernetes docs.

So we have two options to fix this:

- Use individual SolrNode services always, no matter if an Ingress is being used or not. This will eliminate our need for Headless Services.
- Use Port 8983 for non-ingress clouds, and keep the headless service.

We are trying to make addressability a lot more configurable in #68. I think in the short term, we should likely use port 8983 instead of 80 and keep the headless service. But that means that we should definitely not create the headless service when using the ingress. Once this is fixed, we can work on expanding the addressability options.

This should be a relatively straightforward change.

**Comment by gmaiztegi** [comment]
The thing with headless services is that they are just hostnames that resolve to all pods, so there is no port translation from `port` to `targetPort`.

I see that there is a regular/proxy service being created for each one of the pods (`matching-solrcloud-0` in my case), so I guess that you could use that as hostname to make it work on port 80.

By the way, thank you so much for the quick response.

**Comment by HoustonPutman** [comment]
> I see that there is a regular/proxy service being created for each one of the pods (matching-solrcloud-0 in my case), so I guess that you could use that as hostname to make it work on port 80.

The reason for the proxy services is so that an ingress rule can be matched to each individual Solr pod. The solr-operator will set up each solr cloud node with ingress-urls if the `ingress-base-domain` flag is passed in on startup, or with headless-service urls if the flag is not used. Without the ingress being created, there's no need to create the individual services for every pod so that step is skipped. 

So in the PR that I created, the proxy services and common cloud service still use port 80. The headless service is the only one that exposes 8983.

And no worries, I'm glad the fix was quick!

**Comment by gmaiztegi** [comment]
That makes a lot of sense. Thank you so much. Looking forward to see it merged.

**Comment by HoustonPutman** [comment]
This will go out in release `v0.2.3`.

If possible, would you mind testing it out on your clusters to make sure it works as intended before I cut the release? It works on mine, but the more confidence the better.

**Comment by gmaiztegi** [comment]
I tested the PR by building it myself and it worked perfectly. The only issue was that the chart does not have a way to specify image pull secrets, so I might submit a PR for that.

**Comment by HoustonPutman** [comment]
Thanks so much for testing it!

And that'd be amazing. Ping me here on a new issue or on the slack channel if you need help or want to get it reviewed.

**Comment by alewis001** [comment]
Hi there. I'm seeing what appears to be exactly this issue on 0.3.0. I followed the instructions on this page https://apache.github.io/solr-operator/docs/local_tutorial but using minikube rather than the K8s in Docker Desktop. I followed the instructions down to and including this section: https://apache.github.io/solr-operator/docs/local_tutorial#start-an-example-solr-cloud-cluster

At this point I see the NPE as per this issue. Also, I cannot successfully add a collection.

Using `helm list` it outputs:
`solr-operator	fender   	1       	2021-06-18 09:48:29.97069 +0100 BST 	deployed	solr-operator-0.3.0  	v0.3.0`
Which would suggest I've deployed the right version.

Can you please confirm whether this issue has regressed since `v0.2.3` or whether I may have done something wrong. The only deviation from the instructions was that I set the replica count to 1 from 3 (and that I'm using minikube but I don't think that should have any affect AFAIK but I can't discount it).

**Comment by HoustonPutman** [comment]
So can you post some more information? Such as your SolrCloud yaml as well as your Solr logs?

There should not be a headless service exposing port 80 anymore, since that just does not work. I'd be very concerned if the same issue was popping up in `v0.3.0`.

**Comment by alewis001** [comment]
Hi, apologies for not getting back sooner.

I'll re-run through the instructions that I linked to and I'll then get all resources that are deployed to k8s. Hopefully I'll be able to get back to this in the next day or so.

**Comment by alewis001** [comment]
Apologies, it looks like the issue was due to another piece of software that had Solr embedded and the two "instances" we conflicting. Also, sorry it took so long to get back to this.

**Comment by HoustonPutman** [comment]
Glad to hear things are working now!

**Comment by edaemon** [comment]
I'm seeing a similar issue with version 0.9.0, but I'm wondering if there's some configuration I'm missing. The problem I'm having is that requests to the common service seem to internally rely on a connection to the headless service, but those connections are attempted over port 80 instead of 8983. What would cause it to use port 80 for the headless service requests and can that be configured?

The headless service is correctly listening on port 8983:

```
NAME                                                          TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                        AGE
[redacted]-solr-solrcloud-headless                            ClusterIP   None             <none>        8983/TCP                                       3m18s
```

However, when I interact with the common service to try and add a collection I get an error like this:
<details><summary>Error message</summary>
<p>

```
  Creating collection [redacted] failed with error code 400: Solr HTTP error: OK (400)
  {
    "responseHeader":{
      "status":400,
      "QTime":931},
    "failure":{
      "[redacted]-solr-solrcloud-0.[redacted]-solr-solrcloud-headless.[redacted]:80_solr":"org.apache.solr.client.solrj.SolrServerException:
  Server refused connection at: http://[redacted]-solr-solrcloud-0.[redacted]-solr-solrcloud-headless.[redacted]:80/solr"},
    "Operation create caused exception:":"org.apache.solr.common.SolrException:org.apache.solr.common.SolrException: Underlying core creation failed while creating collection: [redacted]",
    "exception":{
      "msg":"Underlying core creation failed while creating collection: [redacted]",
      "rspCode":400},
    "error":{
      "metadata":[
        "error-class","org.apache.solr.common.SolrException",
        "root-error-class","org.apache.solr.common.SolrException"],
      "msg":"Underlying core creation failed while creating collection: [redacted]",
      "code":400}}
```

</p>
</details> 

If I try to create a collection directly with the headless service over port 8983 I get the exact same behavior. Here's the SolrCloud YAML I'm using:

<details><summary>SolrCloud YAML</summary>
<p>

```
# Solr Cloud for the Drupal environment; relies on Solr Operator
---
apiVersion: solr.apache.org/v1beta1
kind: SolrCloud
metadata:
  name: "{{ .Release.Name }}-solr"
spec:
  dataStorage:
    persistent:
      reclaimPolicy: "{{ .Values.solr.reclaimPolicy }}"
      pvcTemplate:
        spec:
          storageClassName: "ebs-sc"
          resources:
            requests:
              storage: "{{ .Values.solr.storage }}"
  replicas: {{ .Values.solr.replicas }}
  solrImage:
    tag: {{ .Values.solr.solrImage }}
  solrJavaMem: "{{ .Values.solr.solrJavaMem }}"
  solrModules:
    - jaegertracer-configurator
    - ltr
  customSolrKubeOptions:
    podOptions:
      resources:
        limits:
          memory: "{{ .Values.solr.resources.limits.memory }}"
        requests:
          cpu: "{{ .Values.solr.resources.requests.cpu }}"
          memory: "{{ .Values.solr.resources.requests.memory }}"
  zookeeperRef:
    provided:
      chroot: "/this/will/be/auto/created"
      persistence:
        spec:
          storageClassName: "ebs-sc"
          resources:
            requests:
              storage: "{{ .Values.solr.zookeeper.storage }}"
      replicas: {{ .Values.solr.zookeeper.replicas }}
      zookeeperPodPolicy:
        resources:
          limits:
            memory: "{{ .Values.solr.zookeeper.resources.limits.memory }}"
          requests:
            cpu: "{{ .Values.solr.zookeeper.resources.requests.cpu }}"
            memory: "{{ .Values.solr.zookeeper.resources.requests.memory }}"
  solrOpts: "{{ .Values.solr.solrOpts }}"
  solrGCTune: "{{ .Values.solr.solrGCTune }}"
  solrAddressability:
    commonServicePort: 8983
```

</p>
</details>

I also tried setting `SolrCloud.Spec.solrAddressability.podPort` to 80 and that did change the port that the headless service was listening on to 80 which may have worked, but that threw errors because the port is privileged and the pod wasn't able to use it.

**Comment by HoustonPutman** [comment]
@edaemon I think there was an issue when you had `podPort=80`, and created replicas. Those now see themselves as living on that port, which you are no longer using. I would recommend re-creating your cloud and removing the custom "solr.port.advertise" (which the operator does set through the `SOLR_PORT_ADVERTISE` envVar). If it still doesn't work after starting from scratch, create a new issue.

**Comment by edaemon** [comment]
@HoustonPutman, thanks for the feedback. I had recreated the cloud many times without the custom `podPort` and saw the same behavior. I did see the `SOLR_PORT_ADVERTISE=8983` envvar but for some reason it was not effective. I'll try again sometime soon and open an issue if I see the same problem.
